#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_placement           second_child \
                window_zoom_persist        off          \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.2          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                insert_feedback_color      0xff74ee15   \
                split_ratio                0.50         \
                auto_balance               off          \
                auto_padding               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          stack        \
                                                        \
                top_padding                10           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 10            
                # auto_padding_min_aspect    2.33       \
                # auto_padding_width         1280       \
                # auto_padding_height        1420

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|System Settings|Software Update|Dictionary|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="Code" opacity=0.95

yabai -m config layout bsp

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=3.0 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
